const groups=['A+','A-','B+','B-','AB+','AB-','O+','O-'];
const stock=[['A+',18],['A-',7],['B+',14],['B-',4],['AB+',9],['AB-',3],['O+',22],['O-',6]];
let donors=[['Demo Donor One','A+','000-000-0101','Chennai'],['Demo Donor Two','O+','000-000-0102','Coimbatore'],['Demo Donor Three','B-','000-000-0103','Madurai'],['Demo Donor Four','AB+','000-000-0104','Trichy']];
let requests=[['Sample Request Alpha','O+',2,'Demo General Hospital','Pending'],['Sample Request Beta','B-',1,'Example Care Centre','Approved']];
const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function paintStock(){const html=stock.map(([g,n])=>`<div class="blood-cell"><div class="blood-type">${g}</div><div class="blood-units">${n}</div><small>units available</small><div class="progress"><i style="width:${Math.min(100,n*5)}%"></i></div></div>`).join('');$('#stock-grid').innerHTML=html;$('#dashboard-stock').innerHTML=html;$('#unit-count').textContent=stock.reduce((a,x)=>a+x[1],0)}
function paintDonors(){$('#donor-rows').innerHTML=donors.map(d=>`<tr>${d.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('');$('#donor-count').textContent=donors.length}
function paintRequests(){$('#request-rows').innerHTML=requests.map(r=>`<tr><td>${esc(r[0])}</td><td><span class="badge danger">${esc(r[1])}</span></td><td>${r[2]}</td><td>${esc(r[3])}</td><td><span class="badge ${r[4]==='Pending'?'warning':'success'}">${r[4]}</span></td></tr>`).join('');$('#pending-count').textContent=requests.filter(r=>r[4]==='Pending').length}
function toast(msg){const t=$('#toast');t.textContent=msg;t.hidden=false;setTimeout(()=>t.hidden=true,3000)}
function navigate(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav-links a').forEach(a=>a.classList.toggle('active',a.hash==='#'+id));history.replaceState(null,'','#'+id);document.querySelector('.nav-links').classList.remove('open');window.scrollTo(0,0)}
document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();navigate(a.hash.slice(1))}));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.go)));$('.menu-toggle').addEventListener('click',e=>{const open=document.querySelector('.nav-links').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open))});
$('#donor-form').addEventListener('submit',e=>{e.preventDefault();const name=$('#d-name').value.trim(),phone=$('#d-phone').value.trim(),city=$('#d-city').value.trim(),group=$('#d-group').value;if(!name||!phone||!city||!group)return;donors.unshift([name,group,phone,city]);e.target.reset();paintDonors();toast('Demo donor added for this browser session.')});
$('#request-form').addEventListener('submit',e=>{e.preventDefault();const name=$('#r-name').value.trim(),group=$('#r-group').value,units=Number($('#r-units').value),phone=$('#r-phone').value.trim(),org=$('#r-org').value.trim();if(!name||!group||!Number.isInteger(units)||units<1||!phone||!org)return;requests.unshift([name,group,units,org,'Pending']);e.target.reset();paintRequests();toast('Demo request added for this browser session.')});
paintStock();paintDonors();paintRequests();const initial=location.hash.slice(1);if(initial&&$('#'+initial))navigate(initial);
