<?php
require_once __DIR__ . '/config.php';
if (session_status() !== PHP_SESSION_ACTIVE) session_start();
$groups=['A+','A-','B+','B-','AB+','AB-','O+','O-'];
if ($_SERVER['REQUEST_METHOD']==='POST') {
    verify_csrf(); $action=$_POST['action']??'';
    if ($action==='delete') { db()->prepare('DELETE FROM donors WHERE id=?')->execute([(int)$_POST['id']]); flash('Donor record deleted.'); redirect('donors.php'); }
    $name=trim((string)($_POST['name']??'')); $blood= (string)($_POST['blood_group']??''); $phone=trim((string)($_POST['phone']??'')); $city=trim((string)($_POST['city']??'')); $date=(string)($_POST['last_donation_date']??'');
    if ($name===''||!in_array($blood,$groups,true)||!preg_match('/^[0-9+()\- ]{7,20}$/',$phone)||$city===''||($date!==''&&!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date))) { flash('Please enter valid details in all required fields.','error'); redirect('donors.php'.(!empty($_POST['id'])?'?edit='.(int)$_POST['id']:'?new=1')); }
    if ($action==='edit') { db()->prepare('UPDATE donors SET name=?,blood_group=?,phone=?,city=?,last_donation_date=? WHERE id=?')->execute([$name,$blood,$phone,$city,$date?:null,(int)$_POST['id']]); flash('Donor details updated.'); }
    else { db()->prepare('INSERT INTO donors(name,blood_group,phone,city,last_donation_date) VALUES(?,?,?,?,?)')->execute([$name,$blood,$phone,$city,$date?:null]); flash('Donor added successfully.'); }
    redirect('donors.php');
}
$editing=null; if(isset($_GET['edit'])) { $q=db()->prepare('SELECT * FROM donors WHERE id=?');$q->execute([(int)$_GET['edit']]);$editing=$q->fetch(); }
$donors=db()->query('SELECT * FROM donors ORDER BY created_at DESC')->fetchAll(); $showForm=isset($_GET['new'])||$editing;
$pageTitle='Donors'; require __DIR__.'/includes/header.php';
?>
<section class="page-head"><div><div class="eyebrow">Donor directory</div><h1>Donors</h1><p class="subtext">Manage fictional donor records for the project demo.</p></div><a class="btn" href="donors.php?new=1">＋ Add donor</a></section>
<?php if($showForm): ?><section class="panel"><div class="panel-title"><h2><?= $editing?'Edit donor':'Register a donor' ?></h2></div><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="<?= $editing?'edit':'add' ?>"><?php if($editing): ?><input type="hidden" name="id" value="<?= (int)$editing['id'] ?>"><?php endif; ?><div class="form-grid"><div class="field"><label for="name">Full name *</label><input id="name" name="name" required maxlength="100" value="<?= e($editing['name']??'') ?>"></div><div class="field"><label for="blood_group">Blood group *</label><select id="blood_group" name="blood_group" required><option value="">Select group</option><?php foreach($groups as $g): ?><option <?= ($editing['blood_group']??'')===$g?'selected':'' ?>><?= e($g) ?></option><?php endforeach; ?></select></div><div class="field"><label for="phone">Phone *</label><input id="phone" name="phone" required maxlength="20" value="<?= e($editing['phone']??'') ?>" placeholder="Demo number"></div><div class="field"><label for="city">City *</label><input id="city" name="city" required maxlength="80" value="<?= e($editing['city']??'') ?>"></div><div class="field"><label for="last_donation_date">Last donation date</label><input type="date" id="last_donation_date" name="last_donation_date" max="<?= date('Y-m-d') ?>" value="<?= e($editing['last_donation_date']??'') ?>"></div></div><div class="form-actions"><button class="btn" type="submit"><?= $editing?'Save changes':'Add donor' ?></button><a class="btn secondary" href="donors.php">Cancel</a></div></form></section><?php endif; ?>
<section class="panel"><div class="panel-title"><h2>Donor records <span class="badge"><?= count($donors) ?></span></h2></div><div class="toolbar"><input type="search" placeholder="Search name, group, city…" aria-label="Search donors" data-filter="#donors-table"></div><?php if(!$donors): ?><div class="empty">No donor records yet. Add a sample donor to get started.</div><?php else: ?><div class="table-wrap"><table id="donors-table"><thead><tr><th>Name</th><th>Blood group</th><th>Phone</th><th>City</th><th>Last donation</th><th>Actions</th></tr></thead><tbody><?php foreach($donors as $d): ?><tr><td><?= e($d['name']) ?></td><td><span class="badge danger"><?= e($d['blood_group']) ?></span></td><td><?= e($d['phone']) ?></td><td><?= e($d['city']) ?></td><td><?= $d['last_donation_date']?e(date('d M Y',strtotime($d['last_donation_date']))):'—' ?></td><td><div class="actions"><a class="btn secondary small" href="donors.php?edit=<?= (int)$d['id'] ?>">Edit</a><form method="post" data-confirm="Delete this donor record?"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= (int)$d['id'] ?>"><button class="btn danger-btn small">Delete</button></form></div></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
<?php require __DIR__.'/includes/footer.php'; ?>
