<?php
require_once __DIR__.'/config.php';$groups=['A+','A-','B+','B-','AB+','AB-','O+','O-'];$statuses=['Pending','Approved','Fulfilled'];
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=$_POST['action']??'';$id=(int)($_POST['id']??0);if($action==='status'&&$id>0&&in_array($_POST['status']??'',$statuses,true)){db()->prepare('UPDATE blood_requests SET status=? WHERE id=?')->execute([$_POST['status'],$id]);flash('Request status updated.');redirect('requests.php');}
$requester=trim((string)($_POST['requester_name']??''));$blood=(string)($_POST['blood_group']??'');$units=filter_var($_POST['units']??null,FILTER_VALIDATE_INT);$phone=trim((string)($_POST['contact_phone']??''));$org=trim((string)($_POST['organization']??''));if($requester===''||!in_array($blood,$groups,true)||$units===false||$units<1||$units>100||!preg_match('/^[0-9+()\- ]{7,20}$/',$phone)||$org===''){flash('Please enter valid request details.','error');redirect('requests.php?new=1');}db()->prepare('INSERT INTO blood_requests(requester_name,blood_group,units,contact_phone,organization) VALUES(?,?,?,?,?)')->execute([$requester,$blood,$units,$phone,$org]);flash('Blood request recorded.');redirect('requests.php');}
$requests=db()->query('SELECT * FROM blood_requests ORDER BY created_at DESC')->fetchAll();$showForm=isset($_GET['new']);$pageTitle='Blood requests';require __DIR__.'/includes/header.php';
?>
<section class="page-head"><div><div class="eyebrow">Request desk</div><h1>Blood requests</h1><p class="subtext">Record sample requests and keep their review status current.</p></div><a class="btn" href="requests.php?new=1">＋ New request</a></section>
<?php if($showForm):?><section class="panel request-form"><div class="panel-title"><h2>Record a blood request</h2></div><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="add"><div class="form-grid"><div class="field"><label for="requester_name">Requester name *</label><input id="requester_name" name="requester_name" required maxlength="100"></div><div class="field"><label for="blood_group">Blood group *</label><select id="blood_group" name="blood_group" required><option value="">Select group</option><?php foreach($groups as $g):?><option><?= e($g) ?></option><?php endforeach;?></select></div><div class="field"><label for="units">Units requested *</label><input id="units" name="units" type="number" min="1" max="100" required></div><div class="field"><label for="contact_phone">Contact phone *</label><input id="contact_phone" name="contact_phone" required maxlength="20" placeholder="Demo number"></div><div class="field full"><label for="organization">Hospital / organization *</label><input id="organization" name="organization" required maxlength="140"></div></div><div class="form-actions"><button class="btn">Submit request</button><a class="btn secondary" href="requests.php">Cancel</a></div></form></section><?php endif;?>
<section class="panel"><div class="panel-title"><h2>Request records <span class="badge"><?= count($requests) ?></span></h2></div><div class="toolbar"><input type="search" placeholder="Search requester, group, organization…" aria-label="Search requests" data-filter="#requests-table"></div><?php if(!$requests):?><div class="empty">No requests recorded yet.</div><?php else:?><div class="table-wrap"><table id="requests-table"><thead><tr><th>Requester</th><th>Group</th><th>Units</th><th>Organization</th><th>Contact</th><th>Received</th><th>Status</th><th>Update</th></tr></thead><tbody><?php foreach($requests as $r):?><tr><td><?= e($r['requester_name']) ?></td><td><span class="badge danger"><?= e($r['blood_group']) ?></span></td><td><?= (int)$r['units'] ?></td><td><?= e($r['organization']) ?></td><td><?= e($r['contact_phone']) ?></td><td><?= e(date('d M Y',strtotime($r['created_at']))) ?></td><td><span class="badge <?= $r['status']==='Fulfilled'?'success':($r['status']==='Pending'?'warning':'') ?>"><?= e($r['status']) ?></span></td><td><form method="post" class="actions"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="status"><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><select name="status" aria-label="Request status"><?php foreach($statuses as $s):?><option <?= $r['status']===$s?'selected':'' ?>><?= e($s) ?></option><?php endforeach;?></select><button class="btn secondary small">Save</button></form></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<?php require __DIR__.'/includes/footer.php';?>
