<?php
require_once __DIR__.'/config.php';
$groups=['A+','A-','B+','B-','AB+','AB-','O+','O-'];
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$units=$_POST['units']??[];$threshold=(int)($_POST['threshold']??5);if($threshold<1||$threshold>500){flash('Threshold must be between 1 and 500.','error');redirect('stock.php');}try{$pdo=db();$pdo->beginTransaction();$stmt=$pdo->prepare('UPDATE blood_stock SET units=?,low_stock_threshold=? WHERE blood_group=?');foreach($groups as $g){$n=filter_var($units[$g]??null,FILTER_VALIDATE_INT);if($n===false||$n<0||$n>10000)throw new InvalidArgumentException('Enter a whole number from 0 to 10000 for each blood group.');$stmt->execute([$n,$threshold,$g]);}$pdo->commit();flash('Blood stock updated.');}catch(Throwable $e){if(db()->inTransaction())db()->rollBack();flash($e instanceof InvalidArgumentException?$e->getMessage():'Could not update stock. Please check your database.','error');}redirect('stock.php');}
$stock=db()->query('SELECT * FROM blood_stock ORDER BY FIELD(blood_group,"A+","A-","B+","B-","AB+","AB-","O+","O-")')->fetchAll();$threshold=(int)($stock[0]['low_stock_threshold']??5);$pageTitle='Blood stock';require __DIR__.'/includes/header.php';
?>
<section class="page-head"><div><div class="eyebrow">Inventory</div><h1>Blood stock</h1><p class="subtext">View and update units available by blood group.</p></div></section>
<section class="panel"><div class="panel-title"><h2>Current availability</h2><span class="badge">8 groups</span></div><div class="blood-grid"><?php foreach($stock as $s):$low=(int)$s['units']<(int)$s['low_stock_threshold'];?><div class="blood-cell <?= $low?'stock-low':'' ?>"><div class="blood-type"><?= e($s['blood_group']) ?></div><div class="blood-units"><?= (int)$s['units'] ?></div><small>units <?= $low?'· Low stock':'available' ?></small><div class="progress"><i style="width:<?= min(100,(int)$s['units']*5) ?>%"></i></div></div><?php endforeach;?></div></section>
<section class="panel"><div class="panel-title"><h2>Update inventory</h2></div><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><div class="form-grid"><?php foreach($stock as $s):?><div class="field"><label for="u-<?= e($s['blood_group']) ?>"><?= e($s['blood_group']) ?> units</label><input id="u-<?= e($s['blood_group']) ?>" name="units[<?= e($s['blood_group']) ?>]" type="number" min="0" max="10000" required value="<?= (int)$s['units'] ?>"></div><?php endforeach;?><div class="field"><label for="threshold">Low-stock threshold (units)</label><input id="threshold" name="threshold" type="number" min="1" max="500" required value="<?= $threshold ?>"></div></div><div class="form-actions"><button class="btn">Save stock levels</button></div></form></section>
<?php require __DIR__.'/includes/footer.php'; ?>
